baseURL = "https://www.hannahkloss.com/"
languageCode = "en-us"
title = "Hannah Kloss-Gleason"
theme = "m10c"
[related]
  threshold = 80
  includeNewer = true
  toLower = true
  [[related.indices]]
    name = "tags"
    weight = 100
  [[related.indices]]
    name = "date"
    weight = 10
[params]
  fullWidthTheme = false
  centerTheme = true
  description = "Hiya! I&#39;m a fantasy writer who dedicates my free time to acting on stage. I graduated from the University at Buffalo with a Bachelor of Arts degree in Computer Science and a Certificate in Game Studies and am now pursuing a career in telling stories through video games."
  menu_item_separator = " - "  
  [[params.social]]
    icon = "linkedIn"
    name = "linkedIn"
    url = "https://www.linkedin.com/in/hannah-kloss/"

 # Red theme
 [params.style]
    darkestColor = "#d35050"
    darkColor = "#353b43"
    lightColor = "#d6d6d6"
    lightestColor = "#d3d3d3"
    primaryColor = "#ffffff"
